# Generated by Django 6.0.1 on 2026-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('address_ar', models.TextField(verbose_name='العنوان بالعربية')),
                ('address_en', models.TextField(blank=True, verbose_name='Address')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكد إن')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='واتساب')),
                ('map_embed', models.TextField(blank=True, verbose_name='رابط خريطة جوجل')),
            ],
            options={
                'verbose_name': 'معلومات الاتصال',
                'verbose_name_plural': 'معلومات الاتصال',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('subtitle_ar', models.CharField(blank=True, max_length=500, verbose_name='العنوان الفرعي بالعربية')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='الصورة')),
                ('button_text_ar', models.CharField(blank=True, max_length=100, verbose_name='نص الزر بالعربية')),
                ('button_text_en', models.CharField(blank=True, max_length=100, verbose_name='Button Text')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='رابط الزر')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شريحة الهيرو',
                'verbose_name_plural': 'شرائح الهيرو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'الصفحة الرئيسية'), ('about', 'عن الكلية'), ('contact', 'اتصل بنا'), ('policies', 'السياسات')], max_length=20, unique=True, verbose_name='الصفحة')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('content_ar', models.TextField(verbose_name='المحتوى بالعربية')),
                ('content_en', models.TextField(blank=True, verbose_name='Content')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوى صفحة',
                'verbose_name_plural': 'محتويات الصفحات',
            },
        ),
    ]
