# Generated by Django 6.0.1 on 2026-01-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='السنة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المادة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المادة بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Course Name')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='Description')),
                ('academic_year', models.PositiveIntegerField(verbose_name='السنة الدراسية')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='الساعات المعتمدة')),
                ('has_lab', models.BooleanField(default=False, verbose_name='يحتوي على معمل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم القسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Department Name')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='صورة القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'أستاذ'), ('ta', 'معيد')], max_length=10, verbose_name='الدور')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='academic.course', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'تعيين مدرس',
                'verbose_name_plural': 'تعيينات المدرسين',
                'ordering': ['course', 'role'],
            },
        ),
    ]
