# Generated by Django 6.0.1 on 2026-01-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المدرس'),
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_department', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.department', verbose_name='القسم'),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstructor',
            unique_together={('course', 'instructor')},
        ),
    ]
