# Generated by Django 6.0.1 on 2026-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 'المستوى 1'), (2, 'المستوى 2'), (3, 'المستوى 3'), (4, 'المستوى 4'), (5, 'المستوى 5'), (6, 'المستوى 6'), (7, 'المستوى 7'), (8, 'المستوى 8'), (9, 'المستوى 9'), (10, 'المستوى 10')], default=1, verbose_name='الفصل الدراسي (المستوى)'),
        ),
    ]
