# Generated by Django 6.0.1 on 2026-01-26 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('assignment_type', models.CharField(choices=[('theory', 'نظري'), ('lab', 'عملي')], max_length=10, verbose_name='نوع الواجب')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='ملف مرفق')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='الدرجة الكاملة')),
                ('due_date', models.DateTimeField(verbose_name='تاريخ التسليم')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.course', verbose_name='المادة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'واجب',
                'verbose_name_plural': 'الواجبات',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('lecture_type', models.CharField(choices=[('theory', 'نظري'), ('lab', 'عملي')], max_length=10, verbose_name='نوع المحاضرة')),
                ('file', models.FileField(blank=True, null=True, upload_to='lectures/', verbose_name='ملف مرفق')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academic.course', verbose_name='المادة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lectures', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات',
                'ordering': ['course', 'order'],
            },
        ),
    ]
