# Generated by Django 6.0.1 on 2026-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateTimeField(verbose_name='تاريخ الفعالية')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='الصورة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فعالية',
                'verbose_name_plural': 'الفعاليات',
                'ordering': ['-date'],
            },
        ),
    ]
