# Generated by Django 6.0.1 on 2026-01-26 20:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('system_manager', 'مدير النظام'), ('supervisor', 'المشرف'), ('teacher', 'الأستاذ'), ('ta', 'المعيد'), ('student', 'الطالب')], default='student', max_length=20, verbose_name='الدور')),
                ('full_name_ar', models.CharField(max_length=200, verbose_name='الاسم الكامل بالعربية')),
                ('full_name_en', models.CharField(blank=True, max_length=200, verbose_name='Full Name in English')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('academic_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='السنة الدراسية')),
                ('university_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم الجامعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.department', verbose_name='القسم')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم الجامعي')),
                ('full_name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('full_name_en', models.CharField(blank=True, max_length=200, verbose_name='Name in English')),
                ('academic_year', models.PositiveIntegerField(verbose_name='السنة الدراسية')),
                ('is_registered', models.BooleanField(default=False, verbose_name='مسجل في النظام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_students', to='academic.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'طالب جامعي',
                'verbose_name_plural': 'الطلاب الجامعيين',
                'ordering': ['university_number'],
            },
        ),
    ]
